name: Marathon

on:
  push:
    branches: [ master ]
    
env:
  VERSION: 1.0.${{github.run_number}}
  PROFILE_WIN_32: win-x86
  PROFILE_WIN_64: win-x64
  PROFILE_LINUX_64: linux-x64
  PROFILE_OSX_64: osx-x64
  SOLUTION_FILE: Marathon.sln
  MARATHON_PROJECT: ${{github.workspace}}\Marathon\Marathon.csproj
  MARATHON_CLI_PROJECT: ${{github.workspace}}\Marathon.CLI\Marathon.CLI.csproj
  NUGET_SOURCE: https://api.nuget.org/v3/index.json

jobs:
  build:
    name: ${{matrix.configuration}}
    runs-on: windows-2022
    strategy:
      matrix:
        configuration: [ Debug, Release ]
        
    steps:
    - name: Clone Marathon
      uses: actions/checkout@v2

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install Microsoft Build Engine
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      working-directory: ${{github.workspace}}
      run: nuget restore ${{env.SOLUTION_FILE}}
      
    - name: Patch Version Information
      run: |
        ./.github/workflows/VersionPatcher.ps1 -projectPath "${{env.MARATHON_PROJECT}}" -version ${{env.VERSION}} -commitID ${{github.sha}}
        ./.github/workflows/VersionPatcher.ps1 -projectPath "${{env.MARATHON_CLI_PROJECT}}" -version ${{env.VERSION}} -commitID ${{github.sha}}

    - name: Build Marathon for Windows (x86)
      working-directory: ${{github.workspace}}
      run: dotnet publish /p:Configuration=${{matrix.configuration}} /p:PublishProfile=${{env.PROFILE_WIN_32}}

    - name: Build Marathon for Windows (x64)
      working-directory: ${{github.workspace}}
      run: dotnet publish /p:Configuration=${{matrix.configuration}} /p:PublishProfile=${{env.PROFILE_WIN_64}}

    - name: Build Marathon for Linux
      working-directory: ${{github.workspace}}
      run: dotnet publish /p:Configuration=${{matrix.configuration}} /p:PublishProfile=${{env.PROFILE_LINUX_64}}

    - name: Build Marathon for macOS
      working-directory: ${{github.workspace}}
      run: dotnet publish /p:Configuration=${{matrix.configuration}} /p:PublishProfile=${{env.PROFILE_OSX_64}}
      
    - name: Upload Marathon Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Marathon-${{matrix.configuration}}
        path: ${{github.workspace}}\Marathon\bin\${{matrix.configuration}}\net6.0\
        
    - name: Upload Marathon.CLI Artifacts for Windows (x86)
      uses: actions/upload-artifact@v2
      with:
        name: Marathon.CLI-${{matrix.configuration}}-${{env.PROFILE_WIN_32}}
        path: ${{github.workspace}}\Marathon.CLI\bin\${{matrix.configuration}}\net6.0\${{env.PROFILE_WIN_32}}\
        
    - name: Upload Marathon.CLI Artifacts for Windows (x64)
      uses: actions/upload-artifact@v2
      with:
        name: Marathon.CLI-${{matrix.configuration}}-${{env.PROFILE_WIN_64}}
        path: ${{github.workspace}}\Marathon.CLI\bin\${{matrix.configuration}}\net6.0\${{env.PROFILE_WIN_64}}\
        
    - name: Upload Marathon.CLI Artifacts for Linux
      uses: actions/upload-artifact@v2
      with:
        name: Marathon.CLI-${{matrix.configuration}}-${{env.PROFILE_LINUX_64}}
        path: ${{github.workspace}}\Marathon.CLI\bin\${{matrix.configuration}}\net6.0\${{env.PROFILE_LINUX_64}}\
        
    - name: Upload Marathon.CLI Artifacts for macOS
      uses: actions/upload-artifact@v2
      with:
        name: Marathon.CLI-${{matrix.configuration}}-${{env.PROFILE_OSX_64}}
        path: ${{github.workspace}}\Marathon.CLI\bin\${{matrix.configuration}}\net6.0\${{env.PROFILE_OSX_64}}\

  publish:
    name: Publish
    runs-on: windows-2022
    steps:
    - name: Clone Marathon
      uses: actions/checkout@v2

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install Microsoft Build Engine
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      working-directory: ${{github.workspace}}
      run: nuget restore ${{env.SOLUTION_FILE}}
      
    - name: Patch Version Information
      run: ./.github/workflows/VersionPatcher.ps1 -projectPath "${{env.MARATHON_PROJECT}}" -version ${{env.VERSION}}

    - name: Create NuGet Package
      run: dotnet pack "${{env.MARATHON_PROJECT}}" /p:Configuration=Release

    - name: Publish to NuGet
      run: dotnet nuget push "${{github.workspace}}\Marathon\bin\Release\BE32.Marathon.${{env.VERSION}}.nupkg" -k ${{secrets.NUGET_KEY}} -s ${{env.NUGET_SOURCE}}