name: Windows

on:
  push:
    branches: [ master ]
    
env:
  VERSION: 1.0.0.${{github.run_number}}
  SOLUTION_FILE: Marathon.sln
  MARATHON_PROJECT: ${{github.workspace}}\Marathon\Marathon.csproj
  MARATHON_CLI_PROJECT: ${{github.workspace}}\Marathon.CLI\Marathon.CLI.csproj

jobs:
  build:
    name: ${{matrix.configuration}}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Debug, Release ]
        
    steps:
    - name: Clone Marathon
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install Microsoft Build Engine
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      working-directory: ${{github.workspace}}
      run: nuget restore ${{env.SOLUTION_FILE}}
      
    - name: Patch Version Information
      run: ./.github/workflows/VersionPatcher.ps1 -projectPath "${{env.MARATHON_PROJECT}}" -version ${{env.VERSION}} -commitID ${{github.sha}}

    - name: Build Marathon
      working-directory: ${{github.workspace}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} ${{env.SOLUTION_FILE}}
      
    - name: Upload Marathon Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Marathon
        path: ${{github.workspace}}\Marathon\bin\${{matrix.configuration}}\net5.0\
        
    - name: Upload Marathon.CLI Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Marathon.CLI
        path: ${{github.workspace}}\Marathon.CLI\bin\${{matrix.configuration}}\net5.0\
